version: "2.1"
services:
  subsync:
    container_name: subsync
    image: subsync:latest
    build:
      context: /path/to/config/subsync
      dockerfile: subsync.Dockerfile
    user: 1001:100 # plex user:users group
    command: /bin/sh -c "python Subsync-headless/subsync.py"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /path/to/config/subsync:/.config
      - /path/to/movies:/movies
      - /path/to/series:/series